
http://127.0.0.1:8000
http://127.0.0.1:8000/about
http://127.0.0.1:8000/products
http://127.0.0.1:8000/admin


## Curl
curl https://unsplash.com/photos/person-holding-brown-eyeglasses-with-green-trees-background-kqguzgvYrtM


#  curl https://images.unsplash.com/photo-1512099053734-e6767b535838\?w\=700\&auto\=format\&fit\=crop\&q\=60\&ixlib\=rb-4.0.3\&ixid\=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z2xhc3Nlc3xlbnwwfHwwfHx8MA%3D%3D --output image.jpeg
